spring:
  application:
    name: gym-system-api
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gym_system}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Onepiece159}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: 7200000